--- 
#- name: "Install logrotate"
#  yum: name=logrotate
#  tags: 
#    - rotate_log

#- name: install the latest version of LogRotate
#  dnf:
#    name: logrotate
#    state: latest    

#- name: "Install logrotate"
#  apt: name=logrotate state=present
#  tags: 
#    - rotate_log

- name: "Generating conf for Logrotation"
  template:
    src: "{{ role_path }}/templates/{{ item.name }}.j2" 
    dest: "/etc/logrotate.d/{{ item.name }}.conf"
  with_items:
    - { name: dcos_conf }
    - { name: elasticsearch_conf }
  tags: 
    - rotate_log
   
    
- name: "Intiating Log Rotation for each configuration."
  command: "logrotate /etc/logrotate.d/{{ item.name }}.conf"
  register: result
  failed_when: "'FAILED' in result.stderr"
  with_items:
    - { name: dcos_conf }
    - { name: elasticsearch_conf }
  tags: 
    - rotate_log




