--- 
#- name: "Install logrotate"
#  yum: name=logrotate
#  tags: 
#    - rotate_log

#- name: install the latest version of LogRotate
#  dnf:
#    name: logrotate
#    state: latest    

- name: "Install logrotate"
  apt: name=logrotate state=present
  tags: 
    - rotate_log

- name: "Generating conf for {{ app_name }}"
  template:
    src: "{{ role_path }}/templates/conf.j2" 
    dest: "/opt/{{ app_name }}.conf"
  tags: 
    - rotate_log
   
    
#- name: "Rotate data from {{ app_name }}"
#  command: "logrotate /etc/logrotate.d/{{ app_name }}.conf"
#  register: result
#  failed_when: "'FAILED' in result.stderr"
#  tags: 
#    - rotate_log




