--- 
#- name: "Install logrotate"
#  yum: name=logrotate
#  tags: 
#    - rotate_log

#- name: install the latest version of LogRotate
#  dnf:
#    name: logrotate
#    state: latest    

#- name: "Install logrotate"
#  apt: name=logrotate state=present
#  tags: 
#    - rotate_log

#- name: "Accumulate conf files to use for dcos"
#  set_fact:
#     conf_to_use:
#       - dcos_conf
#  when: "'dcos' in group_names"

#- name: "Accumulate conf files to use for elastic nodes."
#  set_fact:
#    conf_to_use:
#       - elasticsearch_conf 
#  when: "'elasticsearch-hp-it-cloud' in group_names"

- debug: 
    msg: "{{ ansible_play_hosts | map('extract', hostvars, 'group_names') | list  }}"
  run_once: yes
  register: gps

- name: "Generating conf for Logrotation"
  template:
    src: "{{ role_path }}/templates/{{ item.name }}.j2" 
    dest: "/etc/logrotate.d/{{ item.name }}.conf"
  when: "{{ item.group }} in gps"
  with_items:
      - { name: dcos_conf, group: dcos }
      - { name: elasticsearch_conf, group: elasticsearch-hp-it-cloud }
  tags:
    - rotate_log

#- name: "Intiating Log Rotation for each configuration."
#  command: "logrotate -f /etc/logrotate.d/{{ item }}.conf"
#  register: result
#  failed_when: "'FAILED' in result.stderr"
#  with_items: " {{ conf_to_use }} "
#  tags: 
#    - rotate_log




